@startuml

namespace sf {
    interface Transformable{
      vector2f position
      vector2f scale
      float rotation
    }
    interface Drawable{
        draw(RenderTarget, RenderStates)
    }
    class RenderTarget
    class RenderTexure{
        clear()
        draw(Drawable)
    }   
    class RenderWindow{
          clear()
          draw(Drawable)
          display()
    }
}

class App << Singleton >>{
      -RenderWindow window
      -Config config
      -Clock clock
      -Time deltaTime
      -bool isRunning
      -float fps
      -StateManager stateManager
     void init()
     void run() 
     void exit()
     void update()
     void render()
     bool isRunning() 
     RenderWindow getWindow()
     Clock getClock()
     Time getDeltaTime()
     Config getConfig()
     StateManager getStateManager()
}

class StateManager{
      -stack<State> stateStack
      void push(State *)
      State * pop()
      State * change(State *)
      bool isEmpty()
      void clear()
      void update()
      void render(RenderTarget)
}

abstract class State{
      -Renderer renderer
      update()
}

class Renderer{
      draw(RenderTarget, RenderStates)
}

class Scene{
      -list<GameObject> entities
      void drawEntities(RenderTarget, RenderState)
}

abstract class GameObject{
      void update()
}

abstract class Element{
      -unsigned short health
}

class Player{
      -unsigned short lifes
      -unsigned long score
      -Shape boundingBox
      unsigned short getLifes()
      void setLifes(unsigned short)
      void addLifes(unsigned short)
      void removeLifes(unsigned short)
      unsigned long getScore()
      void setScore(unsigned long)
      void addScore(unsigned long)
      void removeScore(unsigned long)
}


abstract class Component{
}

class Physics{
      -vector2f velocity
      -float rotationForce
      -vector2f growth
      -vector2f acceleration
      -float rotationAcceleration
      -vector2f growthAcceleration
      -double mass
      void update()      
}

class PhysicEngine{
      const float EARTH_GRAVITY
      update(Physics *, GameObject *)
}

App *-- StateManager
StateManager *-- State
State --|> sf.Drawable
State *-- Renderer
Renderer --|> sf.RenderTexure
Scene -left-|> State
Level --|> Scene
Scene o-right- GameObject
GameObject --|> sf.Drawable
Player -left-|> GameObject
Level o-- Player
Component --o GameObject
Component --o Component
Transform --|> Component
Transform --|> sf.Transformable
Physics --|> Component 
'Bullet -left-|> GameObject
Element -left-|> GameObject
Target --|> Element
Enemy --|> Element
'App o-- InputHandler
'Element --|> PhysicObject
'PhysicObject --|> sf.Transformable
sf.RenderWindow --|> sf.RenderTarget
sf.RenderTexture --|> sf.RenderTarget

@enduml