@startuml

package Core <<Rect>> {
}

package Control <<Rect>> {
}

package Collision <<Rect>> {
}

package Audio <<Rect>> {
}

package Rendering <<Rect>> {
}

package Physics <<Rect>> {
}

Core <.up. Control
Collision .left.> Core
Core <.. Audio
Core <.right. Rendering
Core <.down. Physics 

@enduml