@startuml

App *-- StateManager
StateManager o-- State
State <|-- Scene
Scene *-- SceneGraph
SceneGraph o-- GameObject
GameObject o-- Component

Scene *-- Renderer
Scene *-- PhysicEngine
Scene *-- CollisionEngine

App *-- Config
Action .. State
Controller --* State
Controller o-- Action

Component <|-- RenderingComponent
RenderingComponent .. Renderer
Component <|-- PhysicsComponent
PhysicsComponent .. PhysicEngine
Component <|-- ColliderComponent
ColliderComponent .. CollisionEngine


@enduml