Idea for components:
- separate each type of components in modules
- user would have to create new classes to inherit components needed by
  his objects
- doing it all components of an object would be gathered in a single 
  member and accessible directly with their name (like an association 
  list, but without the cost of list)

@startuml

package {
    abstract class SoundComponent
    abstract class D2Component
    abstract class PhysicComponent
    abstract class ConsoleComponent
}

SD2Comp --|> SoundComponent
SD2Comp --|> D2Component

D2PComp --|> PhysicComponent
D2PComp --|> D2Component

SD2PCComp --|> SoundComponent
SD2PCComp --|> PhysicComponent
SD2PCComp --|> D2Component
SD2PCComp --|> ConsoleComponent

ObjA o-- SD2PCComp

ObjB o-- D2PComp

@enduml
