@startuml

class PhysicsComponent{
  Force velocity
  Force rotation
  Force growth
}

class Force<D,T>{
  Vector<D,T> magnitude
  Vector<D,T> acceleration
}

class Vector<D,T>{
  operator+=(Vector)
  operator-=(Vector)
  operator*=(Vector)
  operator*=(T)
  operator/=(Vector)
  operator/=(T)
  operator<<(ostream)
}

namespace std{
 class array        
}

Vector --|> std.array
PhysicsComponent *-- Force : computes
Force --* Vector : strength, acceleration
Force <|-- Force1D : Force<1, float>
Force <|-- Force2D : Force<2, float>
Force <|-- Force3D : Force<3, float>

@enduml