CXX=g++
CXXFLAGS+= -std=c++0x -Wall -Wextra -pedantic-errors -g
LDFLAGS+= -lsfml-audio -lsfml-graphics -lsfml-window -lsfml-system

generic_show:
	@echo "-compiler : $(CXX)"
	@echo "-compiler options : $(CXXFLAGS)"
	@echo "-linker flag : $(LDFLAGS)"

%.d: %.cpp
	$(CXX) $(CXXFLAGS) -M $< > $@

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ -c $<

generic_clean:
	rm -f *.o *.d *.d.* *~ *# *.gch *.gcno *.gcda
